server:
  port:  8081

spring:
  application:
    name: spring-mysql-sharding-app
  
  docker:
    compose:
      enabled: true
      readiness:
        wait: always        # Tells Spring Boot to wait for container health checks
        timeout: 2m
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50 # Bulk inserts
          order_inserts: true
          order_updates: true

# Hikari Connection Pool settings Reusable Anchor)
database:
  hikari-common: &hikari-settings
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    maximum-pool-size: 20 # 20 connection per database
    minimum-idle: 5
    idle-timeout: 300000
    max-lifetime: 1800000 
    connection-timeout: 20000
    pool-name: ShardHikariPool

  datasource:
    lookup:
      jdbc-url: jdbc:mysql://localhost:3307/product_lookup_db?useSSL=false&serverTimezone=UTC
      username: appuser
      password: apppassword
      <<: *hikari-settings

    shard1:
      jdbc-url: jdbc:mysql://localhost:3308/product_shard_1?useSSL=false&serverTimezone=UTC
      username: appuser
      password: apppassword
      <<: *hikari-settings

    shard2:
      jdbc-url: jdbc:mysql://localhost:3309/product_shard_2?useSSL=false&serverTimezone=UTC
      username: appuser
      password: apppassword
      <<: *hikari-settings

    shard3:
      jdbc-url: jdbc:mysql://localhost:3310/product_shard_3?useSSL=false&serverTimezone=UTC
      username: appuser
      password: apppassword
      <<: *hikari-settings

    shard4:
      jdbc-url: jdbc:mysql://localhost:3311/product_shard_4?useSSL=false&serverTimezone=UTC
      username: appuser
      password: apppassword
      <<: *hikari-settings

    shard5:
      jdbc-url: jdbc:mysql://localhost:3312/product_shard_5?useSSL=false&serverTimezone=UTC
      username: appuser
      password: apppassword
      <<: *hikari-settings